"""Phase 5 — recommendation engine demo and worked examples.

    python scripts/run_phase5.py --day Friday --start 17:00 --hours 4
    python scripts/run_phase5.py --rank
    python scripts/run_phase5.py --examples
"""

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd

from driveriq import config as cfg
from driveriq import recommend as R

EXAMPLES = [
    ("Friday", 17.0, 4.0, "The obvious one: straight into evening peak."),
    ("Tuesday", 11.0, 3.0, "Lunch, a mid-strength window."),
    ("Sunday", 14.0, 3.0, "Afternoon — historically the weakest working window."),
    ("Monday", 6.0, 3.0, "Morning: never worked, so the engine must refuse."),
]


def _parse_hour(text: str) -> float:
    if ":" in text:
        hh, mm = text.split(":")
        return int(hh) + int(mm) / 60
    return float(text)


def _format_plan(plan: dict) -> str:
    q = plan["query"]
    lines = [f"{q['day']} from {q['start_hour']:g}:00 for {q['available_hours']:g}h"
             f"  →  {plan['verdict'].replace('_', ' ').upper()}"]

    if plan["expected_earnings"] is None:
        lines.append("  No dollar figure: not enough evidence to answer.")
    else:
        band = plan["band_80"]
        lines.append(f"  Expected ${plan['expected_earnings']:.2f} "
                     f"(80% band ${band[0]:.2f}–${band[1]:.2f}) · "
                     f"${plan['expected_per_available_hour']:.2f}/available hour")

    for w in plan["windows"]:
        if w["status"] == "no_evidence":
            lines.append(f"    {w['window']:<13} {w['hours_covered']:.2g}h — no evidence, excluded")
        else:
            tag = " [thin]" if w["status"] == "thin" else ""
            rated = " pro-rated" if w.get("pro_rated") else ""
            lines.append(
                f"    {w['window']:<13} {w['hours_covered']:.2g}h  "
                f"${w['expected_earnings']:.2f}  n={w['observations']}"
                f"  {w['confidence']}{tag}{rated}"
            )

    stay = plan["stay_advice"]
    lines.append(f"  Stay: about {stay['suggested_session_hours']}h — trips/hour peaks in "
                 f"hour {stay['peak_hour_into_session'] + 1} then falls off")
    if plan.get("alternatives"):
        alts = ", ".join(f"{a['start_hour']}:00 (${a['expected_earnings']:.0f})"
                         for a in plan["alternatives"])
        lines.append(f"  Better starts same day: {alts}")
    return "\n".join(lines)


def _write_examples() -> None:
    lines = ["# DriverIQ — Phase 5: Recommendation Examples", "",
             "Generated by `python scripts/run_phase5.py --examples`.", "",
             "The engine ranks **time windows**, not locations. The README's "
             "location ranking is not supportable: 27 of 33 located sessions share "
             "one cell and 99% of driving falls within 3 km, so there is no second "
             "area to recommend. Location travels through as context instead.", "",
             "Output is structured data, never prose — Phase 6 narrates these "
             "dictionaries rather than recomputing anything.", ""]

    for day, start, hours, note in EXAMPLES:
        plan = R.plan_session(day, start, hours)
        lines += [f"## {day} {start:g}:00, {hours:g} hours", "", f"*{note}*", "",
                  "```", _format_plan(plan), "```", ""]

    ranking = R.rank_windows(top_n=8)
    lines += ["## Best windows across the week", "",
              "| Day | Window | Expected | 80% band | Worked | Confidence |",
              "|---|---|---|---|---|---|"]
    for r in ranking["ranked"]:
        lines.append(f"| {r['day']} | {r['window']} | ${r['expected_earnings']:.2f} | "
                     f"${r['band_80'][0]:.2f}–${r['band_80'][1]:.2f} | "
                     f"{r['observations']} | {r['confidence']} |")
    lines.append("")

    if ranking["never_worked_windows"]:
        lines += [f"**Never worked:** {', '.join(ranking['never_worked_windows'])}. "
                  "The engine returns no figure for these rather than extrapolating.", ""]

    lines += ["## How the engine refuses", "",
              f"A window needs at least {R.MIN_OBSERVATIONS_TO_RANK} recorded "
              "occurrences to be ranked. Below that it is reported but not ranked; "
              "with no history at all the verdict is `not_enough_evidence` and **no "
              "dollar figure is produced**. Declining to answer is a feature here — "
              "without it the engine would rank a window seen twice against one seen "
              "fifty times.", "",
              "Worth being straight about which half of that gate actually fires on "
              "this dataset: every window the driver has worked has at least 14 "
              "occurrences, so the thin-evidence branch is never reached. The refusals "
              "above all come from windows with *no* history at all — morning and "
              "overnight. The threshold is there for a future export, or another "
              "driver, where it would bite.", "",
              "## Caveats carried with every answer", ""]
    lines += [f"- {c}" for c in R.CAVEATS]

    out = cfg.REPORTS_DIR / "phase5_examples.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out.relative_to(cfg.PROJECT_ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--day", default="Friday")
    parser.add_argument("--start", default="17:00")
    parser.add_argument("--hours", type=float, default=4.0)
    parser.add_argument("--rank", action="store_true", help="rank windows instead")
    parser.add_argument("--examples", action="store_true", help="write the report")
    parser.add_argument("--json", action="store_true", help="raw structured output")
    args = parser.parse_args()

    if args.examples:
        ranking = R.rank_windows(top_n=35)
        pd.DataFrame(ranking["ranked"]).to_parquet(
            cfg.PROCESSED_DIR / "window_rankings.parquet", index=False
        )
        _write_examples()
        return

    result = R.rank_windows(args.day if args.day != "all" else None) if args.rank \
        else R.plan_session(args.day, _parse_hour(args.start), args.hours)

    if args.json:
        print(json.dumps(result, indent=2, default=str))
    elif args.rank:
        for r in result["ranked"]:
            print(f"{r['day']:<10} {r['window']:<13} ${r['expected_earnings']:6.2f}  "
                  f"n={r['observations']:<3} {r['confidence']}")
    else:
        print(_format_plan(result))


if __name__ == "__main__":
    main()
