"""Phase 6 — ask the local model a question in plain English.

    python scripts/run_phase6.py --ask "I have 3 hours free Friday evening, worth it?"
    python scripts/run_phase6.py --demo      # run the example set, write the report
    python scripts/run_phase6.py --check     # is Ollama reachable?
"""

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from driveriq import config as cfg
from driveriq import llm

sys.path.insert(0, str(Path(__file__).resolve().parent))
from run_phase5 import _format_plan  # noqa: E402  deterministic fallback text

DEMO_QUESTIONS = [
    "I have 4 hours free on Friday evening, is it worth going out?",
    "When is the best time to drive this week?",
    "How long should I stay out once I start?",
    "Is Sunday afternoon any good?",
    "Which area should I drive in tonight?",
    "Should I work Monday morning?",
]


def _fallback(result: dict) -> str:
    """Plain-figures rendering used whenever the model cannot be trusted or reached."""
    if "query" in result:
        return _format_plan(result)
    return json.dumps(llm.trim(result), indent=2, default=str)


def _ask(question: str, verbose: bool = False) -> dict:
    started = time.time()
    out = llm.answer(question, fallback_formatter=_fallback)
    out["seconds"] = round(time.time() - started, 1)

    print(f"\nQ: {question}")
    print(f"A: {out['answer']}")
    tags = [out.get("source", "?"), f"{out['seconds']}s"]
    if out.get("invented_figures"):
        tags.append(f"REJECTED invented {', '.join(out['invented_figures'])}")
    print(f"   [{' · '.join(tags)}]")
    if verbose and out.get("params"):
        print(f"   parsed: {out['params']}")
    return out


def _write_report(results: list[dict]) -> None:
    lines = [
        "# DriverIQ — Phase 6: Local LLM Interface", "",
        "Generated by `python scripts/run_phase6.py --demo`. "
        f"Model: `{llm.MODEL}` via Ollama, temperature 0.", "",
        "## The split", "",
        "The model appears twice, on either side of the analytics engine, and never",
        "in the middle:", "",
        "```",
        "question -> [parse] -> params -> recommend.py -> dict -> [narrate] -> answer",
        "```", "",
        "Python produces every number. The model only turns a question into parameters,",
        "and a result into a sentence.", "",
        "## Two guards", "",
        "**Normalisation.** The parser returns things like `\"evening\"` where a number",
        "was requested, so its output is repaired in Python before it reaches the engine:",
        "time words map to clock hours, `\"today\"` resolves against the system clock, days",
        "are validated, and hours are clamped. Anything unresolvable produces a clarifying",
        "question rather than a guess.", "",
        "**Faithfulness.** Every dollar figure in the generated answer is checked against",
        "the source data before it is shown. On a mismatch the narration is discarded and",
        "the deterministic figures are printed instead. A model narrating earnings will",
        "eventually invent one; on a money-adjacent tool that has to be impossible to",
        "surface, not merely unlikely. Only money is policed — counts and durations get",
        "restated loosely in ordinary prose, and flagging those would bury the errors",
        "that actually cost something.", "",
        "## Exchanges", "",
    ]

    for r in results:
        lines += [f"**Q — {r['question']}**", "",
                  f"> {r['answer']}", "",
                  f"`source: {r.get('source')}` · `{r['seconds']}s`"]
        if r.get("invented_figures"):
            lines.append(f" · **rejected invented figure(s): {', '.join(r['invented_figures'])}**")
        lines.append("")

    used_llm = sum(1 for r in results if r.get("source") == "llm")
    rejected = sum(1 for r in results if r.get("source") == "fallback_unfaithful")
    mean = sum(r["seconds"] for r in results) / max(len(results), 1)
    lines += ["## Run summary", "",
              f"- Questions: {len(results)}",
              f"- Answered by the model: {used_llm}",
              f"- Narrations rejected for inventing a figure: {rejected}",
              f"- Mean response time: {mean:.1f}s (two model calls per question)", ""]

    out = cfg.REPORTS_DIR / "phase6_examples.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {out.relative_to(cfg.PROJECT_ROOT)}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ask")
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    if args.check:
        print(f"Ollama reachable: {llm.available()}  (model {llm.MODEL})")
        return

    if args.demo:
        results = [_ask(q, args.verbose) for q in DEMO_QUESTIONS]
        _write_report(results)
        return

    _ask(args.ask or DEMO_QUESTIONS[0], args.verbose)


if __name__ == "__main__":
    main()
